version: '3.8'

services:
  backend-test:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    container_name: backend-test-app 